#!/bin/bash

clear
echo "================================================================"
echo "   Stupid Docker - A Command Line Docker Interface for Noobs"
echo "================================================================"
sleep 3




install_docker_debian() {
	# Add Docker's official GPG key:
	sudo apt update
	sudo apt install -y ca-certificates curl
	sudo install -m 0755 -d /etc/apt/keyrings
	sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
	sudo chmod a+r /etc/apt/keyrings/docker.asc

	# Add the repository to Apt sources:
	sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

	sudo apt update
	sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}

install_docker_rhel() {
    	sudo dnf install -y dnf-plugins-core
	sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
	sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}

install_docker_arch() {
    	sudo pacman -Sy --noconfirm docker
}

install_docker_suse() {
    	sudo zypper install -y docker
}

install_docker_centos() {
    	sudo dnf install -y dnf-plugins-core
	sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}

install_docker_fedora() {
	sudo dnf config-manager addrepo --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo
	sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}

install_docker_ubuntu() {
	# Add Docker's official GPG key:
	sudo apt update
	sudo apt install -y ca-certificates curl
	sudo install -m 0755 -d /etc/apt/keyrings
	sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
	sudo chmod a+r /etc/apt/keyrings/docker.asc

	# Add the repository to Apt sources:
	sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF

	sudo apt update
	sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}

start_docker() {
    sudo systemctl enable docker
    sudo systemctl start docker
    sudo usermod -aG docker $USER
    echo "Docker successfuly installed and initialized, re-run './stupid-docker' now"
    newgrp docker
}

pause() {
    read -rp "Press Enter to continue..."
}


if ! command -v docker &> /dev/null; then
    echo "Docker is not installed."
    echo "Which Linux distro are you using?"
    echo "1) Debian"
    echo "2) RHEL"
    echo "3) Arch"
    echo "4) SUSE"
    echo "5) CentOS"
    echo "6) Fedora"
    echo "7) Ubuntu"




    read -rp "Enter choice (1-7): " distro

    case $distro in
        1) install_docker_debian ;;
        2) install_docker_rhel ;;
        3) install_docker_arch ;;
        4)
	echo "The Docker package repository for SLES s390x is no longer maintained and docker updates are no longer supported on SUSE."
	read -rp "Proceed with installation of older version regardless? (yes/no)" reply
	if [[ "$reply" == "yes" ]]; then
	install_docker_suse
	else
	exit 1
	fi
	;;
	5) install_docker_centos ;;
	6) install_docker_fedora ;;
	7) install_docker_ubuntu ;;
        *) echo "Invalid option"; exit 1 ;;
    esac

    start_docker
else
    echo "Docker is already installed."
fi

sleep 2

while true; do
    clear
    echo "=============================="
    echo " Docker Management Menu"
    echo "=============================="
    echo "1) Pull Docker Image"
    echo "2) Search for Docker Image"
    echo "3) List Local Docker Images"
    echo "4) Run Container"
    echo "5) List Running Containers"
    echo "6) List All Containers"
    echo "7) Stop Container"
    echo "8) Start Container (Start a previously run container)"
    echo "9) Remove Container"
    echo "10) Remove Image"
    echo "11) Advanced Docker Command Manual (Type 'q' to exit manual page)"
    echo "12) Exit"
    echo "=============================="

    read -rp "Choose an option: " choice

    case $choice in
        1)
            read -rp "Enter image name followed by a colon and version (e.g ubuntu:22.04). Leave blank to pull latest version: " image
            docker pull "$image"
            pause
            ;;
	2)
	    read -rp "Enter search term (e.g ubuntu or fedora or nginx): " term
	    docker search "$term"
	    pause
	    ;;
        3)
            docker images
            pause
            ;;
        4)
            read -rp "Enter the image name followed by a colon and version (e.g centos:8). Leave blank to use the latest version : " image
            read -rp "Name your container: " cname
            docker run -it --name "$cname" "$image"
            pause
            ;;
        5)
            docker ps
            pause
            ;;
        6)
            docker ps -a
            pause
            ;;
        7)
            read -rp "Enter container ID or name: " cid
            docker stop "$cid"
            pause
            ;;
	8)  
	    read -rp "Enter container ID or name: " cid
	    docker start "$cid"
	    pause
	    ;;
        9)
            read -rp "Enter container ID or name: " cid
            docker rm "$cid"
            pause
            ;;
        10)
            read -rp "Enter image ID or name: " img
            docker rmi "$img"
            pause
            ;;
	11)
	    docker --help | less
            pause
	    ;;
        12)
            echo "Exiting Docker....Goodbye"
            exit 0
            ;;
        *)
            echo "Invalid option"
            sleep 1
            ;;
    esac
done
